/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactInfo = IDL.Record({
  'linkedin' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Project = IDL.Record({
  'title' : IDL.Text,
  'link' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMarketingProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addSocialMediaProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addWebDevProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getMarketingProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getSocialMediaProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getWebDevProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'setContactInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactInfo = IDL.Record({
    'linkedin' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Project = IDL.Record({
    'title' : IDL.Text,
    'link' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addMarketingProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addSocialMediaProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addWebDevProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getMarketingProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getSocialMediaProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getWebDevProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'setContactInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };